SET GLOBAL local_infile = 1;

DROP TABLE IF EXISTS staging_players;
CREATE TABLE staging_players (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PERSON_ID  VARCHAR(10),
    FIRST_NAME VARCHAR(255),
    LAST_NAME  VARCHAR(255),
    HEIGHT     VARCHAR(10),
    WEIGHT     VARCHAR(3),
    POSITION   VARCHAR(25)
) CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/player_bio_common.csv'
INTO TABLE staging_players
CHARACTER SET latin2
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PERSON_ID, FIRST_NAME, LAST_NAME, @DISPLAY_FIRST_LAST, @DISPLAY_LAST_COMMA_FIRST, @DISPLAY_FI_LAST,
    @PLAYER_SLUG, @BIRTHDATE, @SCHOOL, @COUNTRY, @LAST_AFFILIATION, HEIGHT, WEIGHT, @SEASON_EXP,@JERSEY,
    POSITION, @ROSTERSTATUS, @GAMES_PLAYED_CURRENT_SEASON_FLAG, @TEAM_ID, @TEAM_NAME, @TEAM_ABBREVIATION,
    @TEAM_CODE, @TEAM_CITY, @PLAYERCODE, @FROM_YEAR, @TO_YEAR, @DLEAGUE_FLAG, @NBA_FLAG, 
    @GAMES_PLAYED_FLAG, @DRAFT_YEAR, @DRAFT_ROUND, @DRAFT_NUMBER, @GREATEST_75_FLAG
);

DROP TABLE IF EXISTS staging_teams;
CREATE TABLE staging_teams (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(10),
    full_name VARCHAR(50),
    abbreviation VARCHAR(3),
    nickname VARCHAR(25),
    city VARCHAR(25)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/team_information.csv'
INTO TABLE staging_teams
CHARACTER SET latin2
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    id, full_name, abbreviation, nickname, city, @state, @year_founded
);

DROP TABLE IF EXISTS staging_shot_zones;
CREATE TABLE staging_shot_zones (
	row_id INT AUTO_INCREMENT PRIMARY KEY,
    SEASON VARCHAR(10),
    TEAM_ID VARCHAR(10),
    PLAYER_ID VARCHAR(10),
    SHOT_ZONE_BASIC VARCHAR(50),
    SHOT_ZONE_AREA VARCHAR(50),
    SHOT_ZONE_RANGE VARCHAR(50),
    FGM VARCHAR(4),
    FGA VARCHAR(4)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/player_shooting_by_team_season__zones.csv'
INTO TABLE staging_shot_zones
CHARACTER SET latin2
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    SEASON, TEAM_ID, @TEAM_ABBREVIATION, @TEAM_NAME, PLAYER_ID, @PLAYER_NAME, 
    SHOT_ZONE_BASIC, SHOT_ZONE_AREA, SHOT_ZONE_RANGE, FGM, FGA, @FG_PCT
);

DROP TABLE IF EXISTS staging_team_advanced_stats;
CREATE TABLE staging_team_advanced_stats (
	row_id INT AUTO_INCREMENT PRIMARY KEY,
	TEAM_ID VARCHAR(10),
	W VARCHAR(10),
    L VARCHAR(10),
    OFF_RATING VARCHAR(20),
    DEF_RATING VARCHAR(20),
    AST_TO VARCHAR(20),
    EFG_PCT VARCHAR(20),
    TS_PCT VARCHAR(20),
    PACE VARCHAR(20),
    PACE_PER40 VARCHAR(20),
    POSS VARCHAR(10),
    SEASON VARCHAR(10)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/team_advanced_by_season.csv'
INTO TABLE staging_team_advanced_stats
CHARACTER SET latin2
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    TEAM_ID, @TEAM_NAME, @GP, W, L, @W_PCT, @MIN, @E_OFF_RATING, OFF_RATING,
    @E_DEF_RATING, DEF_RATING, @E_NET_RATING, @NET_RATING, @AST_PCT, AST_TO,
    @AST_RATIO, @ORED_PCT, @DREB_PCT, @REB_PCT, @TM_TOV_PCT, EFG_PCT, TS_PCT,
    @E_PACE, PACE, PACE_PER40, POSS, @PIE, @GP_RANK, @W_RANK, @L_RANK, @W_PCT_RANK,
    @MIN_RANK, @OFF_RATING_RANK, @DEF_RATING_RANK, @NET_RATING_RANK, @AST_PCT_RANK,
    @AST_TO_RANK, @AST_RATIO_RANK, @OREB_PCT_RANK, @DREB_PCT_RANK, @REB_PCT_RANK,
    @TM_TOV_PCT_RANK, @EFG_PCT_RANK, @TS_PCT_RANK, @PACE_RANK, @PIE_RANK, SEASON
);

DROP TABLE IF EXISTS seasons;
CREATE TABLE seasons (
    season VARCHAR(9) CHECK (season REGEXP '^[0-9]{4}-[0-9]{2}$') PRIMARY KEY
);

INSERT INTO seasons (season)
SELECT DISTINCT SEASON
FROM staging_speed_distance
WHERE SEASON REGEXP '^[0-9]{4}-[0-9]{2}$';

DROP TABLE IF EXISTS staging_speed_distance;
CREATE TABLE staging_speed_distance (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(10),
    SEASON VARCHAR(9),
    MIN VARCHAR(20),
    DIST_MILES VARCHAR(20),
    DIST_MILES_OFF VARCHAR(20),
    DIST_MILES_DEF VARCHAR(20),
    AVG_SPEED VARCHAR(20),
    AVG_SPEED_OFF VARCHAR(20),
    AVG_SPEED_DEF VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_speeddistance.csv'
INTO TABLE staging_speed_distance
CHARACTER SET latin2
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, MIN,
    @DIST_FEET, DIST_MILES, DIST_MILES_OFF, DIST_MILES_DEF, AVG_SPEED, AVG_SPEED_OFF,
    AVG_SPEED_DEF, SEASON, @PT_MEASURE_TYPE, @TEAM_NAME
);

DROP TABLE IF EXISTS staging_pull_ups;
CREATE TABLE staging_pull_ups (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(10),
    SEASON VARCHAR(10),
    PULL_UP_FGM VARCHAR(20),
    PULL_UP_FGA VARCHAR(20),
    PULL_UP_PTS VARCHAR(20),
    PULL_UP_FG3M VARCHAR(20),
    PULL_UP_FG3A VARCHAR(20),
    PULL_UP_EFG_PCT VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_pullupshot.csv'
INTO TABLE staging_pull_ups
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, @MIN,
    PULL_UP_FGM, PULL_UP_FGA, @PULL_UP_FG_PCT, PULL_UP_PTS, PULL_UP_FG3M,
    PULL_UP_FG3A, @PULL_UP_FG3_PCT, PULL_UP_EFG_PCT, SEASON, @PT_MEASURE_TYPE,
    @TEAM_NAME
);

DROP TABLE IF EXISTS staging_catch_and_shoots;
CREATE TABLE staging_catch_and_shoots (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(10),
    SEASON VARCHAR(9),
    CATCH_SHOOT_FGM VARCHAR(20),
    CATCH_SHOOT_FGA VARCHAR(20),
    CATCH_SHOOT_PTS VARCHAR(20),
    CATCH_SHOOT_FG3M VARCHAR(20),
    CATCH_SHOOT_FG3A VARCHAR(20),
    CATCH_SHOOT_EFG_PCT VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_catchshoot.csv'
INTO TABLE staging_catch_and_shoots
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    SEASON, PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, @MIN,
    CATCH_SHOOT_FGM, CATCH_SHOOT_FGA, @CATCH_SHOOT_FG_PCT, CATCH_SHOOT_PTS,
    CATCH_SHOOT_FG3M, CATCH_SHOOT_FG3A, @CATCH_SHOOT_FG3_PCT, CATCH_SHOOT_EFG_PCT,
    @PT_MEASURE_TYPE, @TEAM_NAME
);


DROP TABLE IF EXISTS staging_drives;
CREATE TABLE staging_drives (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(10),
    SEASON VARCHAR(10),
    DRIVES VARCHAR(20),
    DRIVE_FGM VARCHAR(20),
    DRIVE_FGA VARCHAR(20),
    DRIVE_FTM VARCHAR(20),
    DRIVE_FTA VARCHAR(20),
	DRIVE_PTS VARCHAR(20),
    DRIVE_PTS_PCT VARCHAR(20),
    DRIVE_PASSES VARCHAR(20),
    DRIVE_PASSES_PCT VARCHAR(20),
    DRIVE_AST VARCHAR(20),
    DRIVE_AST_PCT VARCHAR(20),
    DRIVE_TOV VARCHAR(20),
    DRIVE_TOV_PCT VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_drives.csv'
INTO TABLE staging_drives
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, @MIN, DRIVES,
    DRIVE_FGM, DRIVE_FGA, @DRIVE_FG_PCT, DRIVE_FTM, DRIVE_FTA, @DRIVE_FT_PCT,
    DRIVE_PTS, DRIVE_PTS_PCT, DRIVE_PASSES, DRIVE_PASSES_PCT, DRIVE_AST,
    DRIVE_AST_PCT, DRIVE_TOV, DRIVE_TOV_PCT, @DRIVE_PF, @DRIVE_PF_PCT, SEASON,
    @PT_MEASURE_TYPE, @TEAM_NAME
);

DROP TABLE IF EXISTS staging_paint_touches;
CREATE TABLE staging_paint_touches (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(20),
    SEASON VARCHAR(9),
    TOUCHES VARCHAR(20),
    PAINT_TOUCHES VARCHAR(20),
    PAINT_TOUCH_FGM VARCHAR(20),
    PAINT_TOUCH_FGA VARCHAR(20),
    PAINT_TOUCH_FTM VARCHAR(20),
    PAINT_TOUCH_FTA VARCHAR(20),
    PAINT_TOUCH_PTS VARCHAR(20),
    PAINT_TOUCH_PASSES VARCHAR(20),
    PAINT_TOUCH_PASSES_PCT VARCHAR(20),
    PAINT_TOUCH_AST VARCHAR(20),
    PAINT_TOUCH_AST_PCT VARCHAR(20),
    PAINT_TOUCH_TOV VARCHAR(20),
    PAINT_TOUCH_TOV_PCT VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_painttouch.csv'
INTO TABLE staging_paint_touches
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, @MIN, TOUCHES,
    PAINT_TOUCHES, PAINT_TOUCH_FGM, PAINT_TOUCH_FGA, @PAINT_TOUCH_FG_PCT,
    PAINT_TOUCH_FTM, PAINT_TOUCH_FTA, @PAINT_TOUCH_FT_PCT, PAINT_TOUCH_PTS,
	@PAINT_TOUCH_PTS_PCT, PAINT_TOUCH_PASSES, PAINT_TOUCH_PASSES_PCT, PAINT_TOUCH_AST,
    PAINT_TOUCH_AST_PCT, PAINT_TOUCH_TOV, PAINT_TOUCH_TOV_PCT, @PAINT_TOUCH_FOULS,
	@PAINT_TOUCH_FOULS_PCT, SEASON, @PT_MEASURE_TYPE, @TEAM_NAME
);

DROP TABLE IF EXISTS staging_post_touches;
CREATE TABLE staging_post_touches (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(10),
    SEASON VARCHAR(9),
    POST_TOUCHES VARCHAR(20),
    POST_TOUCH_FGM VARCHAR(20),
    POST_TOUCH_FGA VARCHAR(20),
    POST_TOUCH_FTM VARCHAR(20),
    POST_TOUCH_FTA VARCHAR(20),
    POST_TOUCH_PTS VARCHAR(20),
    POST_TOUCH_PASSES VARCHAR(20),
    POST_TOUCH_PASSES_PCT VARCHAR(20),
    POST_TOUCH_AST VARCHAR(20),
    POST_TOUCH_AST_PCT VARCHAR(20),
    POST_TOUCH_TOV VARCHAR(20),
    POST_TOUCH_TOV_PCT VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_posttouch.csv'
INTO TABLE staging_post_touches
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, @MIN, @TOUCHES,
    POST_TOUCHES, POST_TOUCH_FGM, POST_TOUCH_FGA, @POST_TOUCH_FG_PCT, POST_TOUCH_FTM,
    POST_TOUCH_FTA, @POST_TOUCH_FT_PCT, POST_TOUCH_PTS, @POST_TOUCH_PTS_PCT,
    POST_TOUCH_PASSES, POST_TOUCH_PASSES_PCT, POST_TOUCH_AST, POST_TOUCH_AST_PCT,
    POST_TOUCH_TOV, POST_TOUCH_TOV_PCT, @POST_TOUCH_FOULS, @POST_TOUCH_FOULS_PCT,
    SEASON, @PT_MEASURE_TYPE, @TEAM_NAME
);

DROP TABLE IF EXISTS staging_elbow_touches;
CREATE TABLE staging_elbow_touches (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(10),
    SEASON VARCHAR(9),
    TOUCHES VARCHAR(20),
    ELBOW_TOUCHES VARCHAR(20),
    ELBOW_TOUCH_FGM VARCHAR(20),
    ELBOW_TOUCH_FGA VARCHAR(20),
    ELBOW_TOUCH_FTM VARCHAR(20),
    ELBOW_TOUCH_FTA VARCHAR(20),
    ELBOW_TOUCH_PTS VARCHAR(20),
    ELBOW_TOUCH_PASSES VARCHAR(20),
    ELBOW_TOUCH_PASSES_PCT VARCHAR(20),
    ELBOW_TOUCH_AST VARCHAR(20),
    ELBOW_TOUCH_AST_PCT VARCHAR(20),
    ELBOW_TOUCH_TOV VARCHAR(20),
    ELBOW_TOUCH_TOV_PCT VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_elbowtouch.csv'
INTO TABLE staging_elbow_touches
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, @MIN, TOUCHES,
    ELBOW_TOUCHES, ELBOW_TOUCH_FGM, ELBOW_TOUCH_FGA, @ELBOW_TOUCH_FG_PCT,
    ELBOW_TOUCH_FTM, ELBOW_TOUCH_FTA, @ELBOW_TOUCH_FT_PCT, ELBOW_TOUCH_PTS,
    @ELBOW_TOUCH_PTS_PCT, ELBOW_TOUCH_PASSES, ELBOW_TOUCH_PASSES_PCT, 
    ELBOW_TOUCH_AST, ELBOW_TOUCH_AST_PCT, ELBOW_TOUCH_TOV, ELBOW_TOUCH_TOV_PCT,
    @ELBOW_TOUCH_FOULS, @ELBOW_TOUCH_FOULS_PCT, SEASON, @PT_MEASURE_TYPE, @TEAM_NAME
);

DROP TABLE IF EXISTS staging_passes;
CREATE TABLE staging_passes (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(10),
    SEASON VARCHAR(9),
    PASSES_MADE VARCHAR(20),
    PASSES_RECEIVED VARCHAR(20),
    AST VARCHAR(20),
    SECONDARY_AST VARCHAR(20),
    POTENTIAL_AST VARCHAR(20),
    AST_POINTS_CREATED VARCHAR(20),
    AST_TO_PASS_PCT VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_passing.csv'
INTO TABLE staging_passes
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, @MIN,
    PASSES_MADE, PASSES_RECEIVED, AST, @FT_AST, SECONDARY_AST, POTENTIAL_AST,
    AST_POINTS_CREATED, @AST_ADJ, AST_TO_PASS_PCT, @AST_TO_PASS_PCT_ADJ,
    SEASON, @PT_MEASURE_TYPE, @TEAM_NAME
);

DROP TABLE IF EXISTS staging_possessions;
CREATE TABLE staging_possessions (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(10),
    SEASON VARCHAR(9),
    TOUCHES VARCHAR(20),
    FRONT_CT_TOUCHES VARCHAR(20),
    TIME_OF_POSS VARCHAR(20),
    AVG_SEC_PER_TOUCH VARCHAR(20),
    AVG_DRIB_PER_TOUCH VARCHAR(20),
    PTS_PER_TOUCH VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_possessions.csv'
INTO TABLE staging_possessions
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, @MIN, @POINTS,
    TOUCHES, FRONT_CT_TOUCHES, TIME_OF_POSS, AVG_SEC_PER_TOUCH, AVG_DRIB_PER_TOUCH,
    PTS_PER_TOUCH, @ELBOW_TOUCHES, @POST_TOUCHES, @PAINT_TOUCHES,
    @PTS_PER_ELBOW_TOUCH, @PTS_PER_POST_TOUCH, @PTS_PER_PAINT_TOUCH, SEASON,
    @PT_MEASURE_TYPE, @TEAM_NAME
);

DROP TABLE IF EXISTS staging_efficiency;
CREATE TABLE staging_efficiency (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID VARCHAR(10),
    TEAM_ID VARCHAR(10),
    SEASON VARCHAR(9),
    POINTS VARCHAR(20),
    EFF_FG_PCT VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/tracking_efficiency.csv'
INTO TABLE staging_efficiency
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    PLAYER_ID, @PLAYER_NAME, TEAM_ID, @TEAM_ABBREVIATION, @GP, @W, @L, @MIN, POINTS,
    @DRIVE_PTS, @DRIVE_FG_PCT, @CATCH_SHOOT_PTS, @CATCH_SHOOT_FG_PCT, @PULL_UP_PTS,
    @PULL_UP_FG_PCT, @PAINT_TOUCH_PTS, @PAINT_TOUCH_FG_PCT, @POST_TOUCH_PTS,
    @POST_TOUCH_FG_PCT, @ELBOW_TOUCH_PTS, @ELBOW_TOUCH_FG_PCT, EFF_FG_PCT, SEASON,
    @PT_MEASURE_TYPE, @TEAM_NAME
);









